### ISSUE TITLE
licenses are not detected

### ISSUE THREAD

**Issue by arcturus140** [fsfe/reuse-example#1]
Using `reuse lint` the following files have no license:

```
Makefile
README.md
.git
img/cat.jpg
img/dog.jpg
src/main.c
```

I had to remove colons to detect licenses, for example:

```
<!--
SPDX-Copyright: 2019 Jane Doe <jane@example.com>

SPDX-License-Identifier: GPL-3.0-or-later
-->
```

into

```
<!--
SPDX-Copyright 2019 Jane Doe <jane@example.com>

SPDX-License-Identifier: GPL-3.0-or-later
-->
```

Using `reuse, version 0.3.4` on Linux Ubuntu 16.04.

# Steps to replicate

1. checkout this repository
2. call `reuse lint` in root directory

**Comment by carmenbianca** [comment]
> reuse, version 0.3.4

This is an older version of reuse. It does not support `SPDX-Copyright:` as a tag. It only supports:

    Copyright author
    © author

The new version is not yet released on PyPI.
