### ISSUE TITLE
Spacing issues in text of license files

### ISSUE THREAD

**Issue by jeremykohn** [fsfe/reuse-example#5]
In the license files [CC-BY-4.0.txt], [CC0-1.0.txt], and [GPL-3.0-or-later.txt], the text looks mostly the same as the plaintext from the licenses' official sources ([CC BY 4.0], [CC0 1.0], [GPL 3.0]) -- except for the spacing.

Some differences are stylistic (indentation, centering) and others are clear errors (missing blank lines, misplaced carriage returns, and extra spaces in the middle of a URL).

So, would it be better to change the license files to exactly match the copy/pasted official plaintext? Or should these files be left as is? Or some third option?

[CC-BY-4.0.txt]: https://github.com/fsfe/reuse-example/blob/master/LICENSES/CC-BY-4.0.txt
[CC0-1.0.txt]: https://github.com/fsfe/reuse-example/blob/master/LICENSES/CC0-1.0.txt
[GPL-3.0-or-later.txt]: https://github.com/fsfe/reuse-example/blob/master/LICENSES/GPL-3.0-or-later.txt

[CC BY 4.0]: https://creativecommons.org/licenses/by/4.0/legalcode.txt
[CC0 1.0]: https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt
[GPL 3.0]: https://www.gnu.org/licenses/gpl-3.0.txt

**Comment by mxmehl** [comment]
Thank you for your report. We take the license texts from SPDX, namely https://github.com/spdx/license-list-data/tree/master/text

As it seems these files were really having a few issues in 2019. I've downloaded the newest versions and force-pushed them to this repo, to keep this example how one commit make the repo compliant.

Apart from that, we are not intending to manually maintain license text versions if they don't fully match with the license creators' versions. For this, please flag such an issue at SPDX.
